### ISSUE TITLE
You must specify POSTGRES_PASSWORD error message

### ISSUE THREAD

**Issue by dany-eudes** [NarHakobyan/awesome-nest-boilerplate#45]
I pulled the postgress-11-alpine fresh image, where in the new image we should specify Postgres user password. 

As the error message is self explainatory:

> You must specify POSTGRES_PASSWORD to a non-empty value for the superuser. 
> For example, "-e POSTGRES_PASSWORD=password" on "docker run".
> 
> You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
> connections without a password. This is *not* recommended.

So, this "POSTGRES_PASSWORD environment variable is required for you to use the PostgreSQL image. It must not be empty or undefined. This environment variable sets the superuser password for PostgreSQL. The default superuser is defined by the POSTGRES_USER environment variable."  See at https://hub.docker.com/_/postgres 

```yaml
version: '3'
services:
  app:
    env_file:
      - .development.env
    container_name: awesome_nest_boilerplate
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_pass
```

Hope this would help anyone.
